import fs from "fs";
import path from "path";
import { GenerationInput, GenerationOutput } from "./types";

export function generateProject(
  input: GenerationInput
): GenerationOutput {
  const basePath = path.join(process.cwd(), input.name);

  if (!fs.existsSync(basePath)) {
    fs.mkdirSync(basePath);
  }

  const readme = `# ${input.name}

${input.description}

Generated by Gitx.
`;

  fs.writeFileSync(
    path.join(basePath, "README.md"),
    readme
  );

  return {
    path: basePath,
    createdAt: new Date().toISOString(),
  };
}
